# Generated by Django 4.0.5 on 2022-06-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='raza',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.cliente'),
        ),
    ]
